- name: Install pakages
  yum:
    name: "{{ item }}"
    state: present
  loop: 
    - vsftpd
    
- name:  Copy the VSFTPD configuration file
  template: 
    src: vsftpd.conf
    dest: "{{ VSFTPD_CONF_PATH }}"
    owner: apache
    group: apache 

- name: start service VSFTPD
  service: 
    name: "{{ VSFTPD_SERVICE }}"
    state: started
    enabled: yes

- name: Check status of VSFTPD service
  service_facts:
  register: service_state
- debug:
    var: service_state.ansible_facts.services["vsftpd.service"].state  
     
- name: open 20\21 ports
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    state: enabled
  notify: Reload firewalld
  loop:
    - 20/tcp
    - 21/tcp