- name: Install pakages
  yum:
    name: "{{ item }}"
    state: present
  loop: 
    - vsftpd
    
- name:  Copy the VSFTPD configuration file
  template: 
    src: vsftpd.conf
    dest: "{{ VSFTPD_CONF_PATH }}"
    owner: root
    group: root

- name: start service VSFTPD
  service: 
    name: "{{ VSFTPD_SERVICE }}"
    state: started
    enabled: yes

- name: Set ftpd_anon_write flag on and keep it persistent across reboots
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes

- name: Set ftpd_full_access flag on and keep it persistent across reboots
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes
 
- name: Check status of VSFTPD service
  service_facts:
  register: service_state
- debug:
    var: service_state.ansible_facts.services["vsftpd.service"].state  
     
- name: open 20\21 ports
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  notify: Reload firewalld
  loop:
    - 20/tcp
    - 21/tcp