---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: True
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: create default doc root
      file: 
        path: /var/www/html/index.html
        state: touch
        owner: apache
        group: apache
      copy:
        content: Welcome to my web server
        dest:  /var/www/html/index.html
    - name: start service apache
      service: 
        name: httpd
        state: started
        enabled: yes
    - name: enable httpd service   
    - name: open httpd port
      firewalld: 
        port: 80/tcp
        state: enabled
        zone: public
        permanent: yes