---
---
- hosts: all
  gather_facts: True
  tasks:
    - include_vars: 
        dir: vars
        files_matching: users.yaml
    
    - name: Add users | create users, shell, home dirs
      user: 
        name: "{{ item.username }}" 
        shell: /bin/bash 
        createhome: yes 
        comment: '{{ item.username }}@example.com'
        password: "{{ 'default_user_password' | password_hash('sha512','A512') }}"
      with_items: "{{users}}"

